track: ETHZMobil
raceline: embmpc/tracks/src/ethzMobil_raceline_long_.npz
centerline: embmpc/tracks/src/ethzMobil_center.txt
inner_boundary: embmpc/tracks/src/ethzMobil_inner.txt
outer_boundary: embmpc/tracks/src/ethzMobil_outer.txt
model_bank_sizes:
  - 5000
  - 10000
  - 20000
scenarios:
  - no_change
  - sudden_drop
  - gradual_decay
  - staged_decay
  - early_drop
  - late_drop
entry_points:
  emb_mpc_single: embmpc.mpc.run_nmpc_orca_embmpc_unknown_detector
  lla_mpc_rt: embmpc.mpc.run_nmpc_orca_llampc_rt
  lla_mpc_nrt: embmpc.mpc.run_nmpc_orca_llampc_nrt
  apacrace: embmpc.mpc.run_nmpc_apacrace
  oracle: embmpc.mpc.run_nmpc_oracle
